In [1]:
import numpy as np

#### Numpy Dizileri

In [3]:
my_list = [10,20,30,40]
type(my_list)

list

In [8]:
# np.array() ile dizi oluşturuyoruz.
my_list = np.array(my_list)

In [9]:
# Yeni type ndarray oluyor.
type(my_list)

numpy.ndarray

In [10]:
my_list.max() # maximum değeri getirir.

np.int64(40)

In [24]:
print(np.ones(5)) # içerisinde 5 tane 1 olan dizi oluşturur.
print(np.zeros(5)) # içerisinde 5 tane 0 olan dizi oluşturur.
print(np.random.random(5)) # içerisinde 5 tane random sayı olan dizi oluşturur.

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0.22984767 0.38455136 0.48554419 0.74691985 0.09747786]


In [25]:
my_list_1 = [1,2]
my_list_2 = [3,4]
my_list_1 + my_list_2

[1, 2, 3, 4]

In [28]:
# Numpy'de diziler toplanırken normaldeki gibi yan yana yazılmaz. Değerleri toplar.
yeni_toplam = np.array(my_list_1) + np.array(my_list_2)
yeni_toplam

array([4, 6])

#### Numpy Indexler

In [29]:
# arange & indexing

In [31]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [33]:
my_np_array = np.arange(0,10)
my_np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# normal diziler gibi indexing yapısı vardır.
print(my_np_array[0])
print(my_np_array[-1])
print(my_np_array[3:5])

0
9
[3 4]


In [39]:
np.random.randn(4,4) # 4x4 bir matris oluşturur. Sayılar rastgeledir.

array([[-0.24583815, -1.22173576, -1.22347431,  1.19964315],
       [ 1.29674483, -0.9383062 ,  1.26578781, -0.72331534],
       [ 0.34221452,  1.34657593,  2.25884476, -0.53253638],
       [ 1.15939923, -0.38037259,  1.27335394,  0.28017236]])

In [43]:
np.random.randint(1,300,5) # 1 ile 300 arasında 5 tane rastgele değer üretir. 

array([ 71, 275, 169,  77, 257])