In [1]:
import numpy as np

#### Numpy Matrix 

In [2]:
my_matrix = [[1,2],[3,4]]
my_matrix[1]

[3, 4]

In [ ]:
# row    = sıra 
# column = kolon

In [8]:
numpy_matrix = np.array([[1,2],[3,4]])
numpy_matrix

array([[1, 2],
       [3, 4]])

In [9]:
numpy_matrix[1,0]

np.int64(3)

In [18]:
np.ones((4,3)) # 4 row, 3 column

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.random.randn(4,3)

array([[ 0.36578086, -1.53153248, -0.18071762],
       [-0.35308844,  0.8992291 , -0.9522789 ],
       [ 0.60509549, -0.23463845,  0.04132362],
       [ 0.19402319, -1.65042021, -0.0436904 ]])

In [20]:
first_array = np.array([[10,20],[30,40]])
second_array= np.array([[5,15],[25,35]])

In [34]:
first_array + second_array # Aynı index'e sahip olan değerleri toplar ve shape'i bozmaz.

array([[15, 35],
       [55, 75]])

In [35]:
third_array = np.array([30,50])
third_array

array([30, 50])

In [36]:
first_array+ third_array 
# Böyle bir durumda column sayıları uyduğu için broadcast yapar ve 
# sanki altında varmış gibi davranır

array([[40, 70],
       [60, 90]])

In [37]:
fourth_array = np.array([[10],[20]])
fourth_array

array([[10],
       [20]])

In [38]:
first_array + fourth_array 
# Biraz önceki ile aynı mantıkta. Burada da raw sayıları aynı olduğu için broadcast yaptı.

array([[20, 30],
       [50, 60]])

#### Matrix Multiplication

In [43]:
print(first_array,"\n")
print(second_array)

[[10 20]
 [30 40]] 

[[ 5 15]
 [25 35]]


In [45]:
#dot product
first_array.dot(second_array)

array([[ 550,  850],
       [1150, 1850]])