In [1]:
import numpy as np

In [3]:
new_array = np.random.randint(1,100,20)
new_array

array([35, 88, 71, 21, 29, 16, 76,  5, 80, 64, 45, 60, 44, 99, 11, 18,  6,
       17, 73, 72])

In [4]:
new_array[new_array>40]

array([88, 71, 76, 80, 64, 45, 60, 44, 99, 73, 72])

In [5]:
# transpose & reshape

In [6]:
matrix_array = np.array([[10,20,30],[45,55,65]])
matrix_array.shape

(2, 3)

In [8]:
matrix_array

array([[10, 20, 30],
       [45, 55, 65]])

In [9]:
matrix_array.transpose() # 2,3 olan shape'i 3,2 olarak değiştirir. Transpozunu alır.

array([[10, 45],
       [20, 55],
       [30, 65]])

In [12]:
random_array = np.random.random((1,6))
random_array

array([[0.87802099, 0.52595212, 0.9040436 , 0.39497735, 0.31954686,
        0.33916073]])

In [14]:
random_array.reshape(3,2) # Dizimizin shape'ini yeniden şekillendirir.

array([[0.87802099, 0.52595212],
       [0.9040436 , 0.39497735],
       [0.31954686, 0.33916073]])