In [1]:
import  torch 
import numpy as np

In [2]:
# Pytorch Datatypes - Tensors

In [3]:
scaler = torch.tensor(10)

In [4]:
torch.tensor([10,20])

tensor([10, 20])

In [5]:
type(scaler)

torch.Tensor

In [6]:
scaler + 5

tensor(15)

In [7]:
scaler * 4

tensor(40)

In [8]:
scaler.dim() # Kaç boyutlu olduğunu söyler

0

In [9]:
scaler.shape 

torch.Size([])

In [10]:
scaler.item()

10

In [11]:
numpy_int = np.int32(10)
numpy_int

np.int32(10)

In [12]:
numpy_int + 120

np.int32(130)

In [13]:
scaler_from_np = torch.tensor(numpy_int)
scaler_from_np

tensor(10, dtype=torch.int32)

In [14]:
scaler.dtype

torch.int64

In [15]:
new_scaler = torch.tensor(25, dtype=torch.int32)

In [16]:
new_scaler.dtype

torch.int32

In [17]:
tensor_float = torch.tensor(3.14)
tensor_float.dtype

torch.float32

In [18]:
tensor_float_64 = torch.tensor(3.1400, dtype=torch.float64)
tensor_float_64.dtype

torch.float64

In [27]:
vector = torch.tensor([2,3,4],)
print(vector.ndim) # atribute
print(vector.dim()) # function

1
1


In [31]:
vector.shape 

torch.Size([3])

---
* Scaler -> 0 boyutlu
* Vector -> 1 boyutlu
* Matrix -> 2 boyutlu
* Tensor -> 3 boyutlu
---

In [32]:
# count # of [ -> dimension
# count elements -> shape

In [42]:
matrix = torch.tensor([[1,2,3],[3,4,0]])
matrix.shape

torch.Size([2, 3])

In [43]:
matrix.dim()

2

In [55]:
tensor_example = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [56]:
tensor_example.dim()

3

In [57]:
tensor_example.shape

torch.Size([1, 3, 3])

In [73]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, # cpu,gpu
                               requires_grad = False # öğrenme yapılabilsin mi
                              )
float_32_tensor.dtype

torch.float32

In [80]:
float_16_tensor = torch.tensor([1.1,2.0,3.0],dtype=int)

In [81]:
float_16_tensor.dtype

torch.int64

In [82]:
float_16_tensor

tensor([1, 2, 3])