In [1]:
import numpy as np
import torch 

In [8]:
random_array = np.random.randn(4,5)
print(random_array)
print(random_array.ndim)
print(random_array.shape)
print(random_array.dtype)

[[-0.75583199  0.24108705 -2.09193427  0.70763459  1.40662622]
 [-0.66855118  0.60077249  0.40093653  1.34077111  1.0925232 ]
 [-2.73964326  2.63091765 -1.46588976 -0.28592931  0.22121555]
 [ 1.04100956 -1.50125544  0.1680075  -0.65987916  1.89730394]]
2
(4, 5)
float64


In [9]:
torch_matrix = torch.rand(3,5)
print(torch_matrix)
print(torch_matrix.ndim)
print(torch_matrix.shape)
print(torch_matrix.dtype)

tensor([[0.9510, 0.7126, 0.4747, 0.5699, 0.6399],
        [0.3220, 0.9191, 0.3239, 0.0336, 0.2116],
        [0.9884, 0.1495, 0.5732, 0.8597, 0.6504]])
2
torch.Size([3, 5])
torch.float32


In [12]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[0.7355, 0.6844, 0.8844],
         [0.7795, 0.3254, 0.4375],
         [0.7848, 0.0635, 0.6238],
         ...,
         [0.2364, 0.8787, 0.2815],
         [0.9665, 0.2796, 0.0903],
         [0.1296, 0.8336, 0.9772]],

        [[0.0315, 0.9569, 0.9047],
         [0.7692, 0.8409, 0.6207],
         [0.2034, 0.8971, 0.6861],
         ...,
         [0.6744, 0.4606, 0.7494],
         [0.7072, 0.1849, 0.8381],
         [0.1867, 0.8584, 0.5415]],

        [[0.6729, 0.2294, 0.7908],
         [0.4777, 0.1929, 0.4966],
         [0.0946, 0.6698, 0.4919],
         ...,
         [0.0831, 0.1295, 0.9776],
         [0.3467, 0.9513, 0.2071],
         [0.5884, 0.2829, 0.6350]],

        ...,

        [[0.2552, 0.3875, 0.9853],
         [0.5020, 0.4035, 0.5390],
         [0.0268, 0.9384, 0.4058],
         ...,
         [0.0734, 0.9065, 0.9984],
         [0.5124, 0.0354, 0.6830],
         [0.3195, 0.3687, 0.1966]],

        [[0.1116, 0.5515, 0.1653],
         [0.2915, 0.6579, 0.5002],
         [0.

In [14]:
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

torch.Size([224, 224, 3])
3


In [16]:
zeros = torch.zeros(size=(3,2),dtype=int)
zeros

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [17]:
ones = torch.ones(size=(5,5),dtype=int)
ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [18]:
vector_with_arange = torch.arange(start=10,end=100,step=3)
vector_with_arange

tensor([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61,
        64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [19]:
similar_ones = torch.ones_like(input=vector_with_arange)
similar_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1])

In [23]:
x_tensor = torch.tensor([1,2,3])
print(x_tensor + 15)
print(x_tensor * 3.14)

tensor([16, 17, 18])
tensor([3.1400, 6.2800, 9.4200])


In [25]:
print(x_tensor.subtract(10)) # Çıkartma
print(x_tensor.multiply(3))  # Çarpma
print(x_tensor.add(20))      # Toplama
print(x_tensor.divide(4))    # Bölme
print(x_tensor)

tensor([-9, -8, -7])
tensor([3, 6, 9])
tensor([21, 22, 23])
tensor([0.2500, 0.5000, 0.7500])
tensor([1, 2, 3])


In [26]:
x_tensor * x_tensor

tensor([1, 4, 9])

In [30]:
y_tensor = torch.tensor([4,5])
print(y_tensor)

tensor([4, 5])


In [29]:
x_tensor + y_tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0