In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.tensor([1,2,3])
tensor * tensor

tensor([1, 4, 9])

In [3]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [6]:
matrix @ matrix # @ işareti matrix çarpımı yapar.

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [8]:
torch.matmul(matrix,matrix) # matmul matrix multiplication 

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [10]:
matrix.size()

torch.Size([3, 3])

In [11]:
tensor1 = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor2 = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

In [14]:
print(tensor1.shape)
print(tensor2.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [16]:
#torch.matmul(tensor1, tensor2) # 3x2 ve 3x2 matrisi çarpamazsın.

In [17]:
tensor2

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [25]:
tensor2.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [26]:
torch.matmul(tensor1,tensor2.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [32]:
A = torch.tensor([[1,2,3]])
print(A.ndim)
print(A.shape)

2
torch.Size([1, 3])


In [33]:
B = torch.tensor([[4],[5],[6]])
print(B.ndim)
print(B.shape)

2
torch.Size([3, 1])


In [ ]:
torch.mutmul(A,B)