In [1]:
import torch

In [2]:
tensor = torch.arange(0,50,5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [3]:
tensor.min() # minimum değeri verir

tensor(0)

In [4]:
tensor.max() # maximum değeri verir.

tensor(45)

In [5]:
tensor.sum() # içerisindeki verileri toplar.

tensor(225)

In [6]:
tensor.median() # medyanını buluruz.

tensor(20)

In [7]:
# tensor.mean() # Bu hata verir.

In [8]:
tensor = tensor.type(torch.float)
tensor.mean()
# Önce float'a çeviriyoruz ondan sonra ortalamsını alıyoruz.

tensor(22.5000)

In [9]:
#argmax, argmin

In [10]:
tensor.argmax() # maximum değerin indexini bize verir.

tensor(9)

In [11]:
tensor.argmin() # minimum değerin indexini bize verir.

tensor(0)

In [12]:
random_matrix = torch.rand(4,5)
random_matrix

tensor([[0.0605, 0.0831, 0.5726, 0.9983, 0.6711],
        [0.0140, 0.4267, 0.9414, 0.8379, 0.3853],
        [0.8025, 0.3396, 0.4475, 0.7808, 0.2247],
        [0.2483, 0.5460, 0.9258, 0.0535, 0.6680]])

In [13]:
print(random_matrix.sum())
print(random_matrix.mean())
print(random_matrix.median())

tensor(10.0278)
tensor(0.5014)
tensor(0.4475)


In [14]:
# manipulating tensor : reshaping, stacking, squeezing, unsqueezing

In [15]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(x.shape)
print(x.ndim)

torch.Size([9])
1


In [17]:
# Elimizdeki verinin boyutunu değiştirmek için kullanılır. -> reshape()
x_reshaped = x.reshape(1,9)
print(x_reshaped)
print(x_reshaped.shape)
print(x_reshaped.ndim)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])
2


In [18]:
# view

In [19]:
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [20]:
x_reshaped[0] = 20

In [21]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [22]:
x_view = x.view(9,1)
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [23]:
x_view[0] = 10
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [24]:
# view -> contigious tensor (ramde veriler sıralı mı?)

In [26]:
x = torch.tensor([[1,2,3],
                  [3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [28]:
x.is_contiguous()

True

In [30]:
y = x.T

In [32]:
y

tensor([[1, 3],
        [2, 4],
        [3, 5]])

In [35]:
y.is_contiguous() # transpoze edilmesi durumunda contiguous durumu bozulabilir.

False

In [ ]:
x.