In [1]:
import torch

In [2]:
tensor = torch.arange(0,50,5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [3]:
tensor.min() # minimum değeri verir

tensor(0)

In [4]:
tensor.max() # maximum değeri verir.

tensor(45)

In [5]:
tensor.sum() # içerisindeki verileri toplar.

tensor(225)

In [6]:
tensor.median() # medyanını buluruz.

tensor(20)

In [7]:
# tensor.mean() # Bu hata verir.

In [8]:
tensor = tensor.type(torch.float)
tensor.mean()
# Önce float'a çeviriyoruz ondan sonra ortalamsını alıyoruz.

tensor(22.5000)

In [9]:
#argmax, argmin

In [10]:
tensor.argmax() # maximum değerin indexini bize verir.

tensor(9)

In [11]:
tensor.argmin() # minimum değerin indexini bize verir.

tensor(0)

In [12]:
random_matrix = torch.rand(4,5)
random_matrix

tensor([[0.0605, 0.0831, 0.5726, 0.9983, 0.6711],
        [0.0140, 0.4267, 0.9414, 0.8379, 0.3853],
        [0.8025, 0.3396, 0.4475, 0.7808, 0.2247],
        [0.2483, 0.5460, 0.9258, 0.0535, 0.6680]])

In [13]:
print(random_matrix.sum())
print(random_matrix.mean())
print(random_matrix.median())

tensor(10.0278)
tensor(0.5014)
tensor(0.4475)


In [14]:
# manipulating tensor : reshaping, stacking, squeezing, unsqueezing

In [15]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(x.shape)
print(x.ndim)

torch.Size([9])
1


In [17]:
# Elimizdeki verinin boyutunu değiştirmek için kullanılır. -> reshape()
x_reshaped = x.reshape(1,9)
print(x_reshaped)
print(x_reshaped.shape)
print(x_reshaped.ndim)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])
2


In [18]:
# view

In [19]:
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [20]:
x_reshaped[0] = 20

In [21]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [22]:
x_view = x.view(9,1)
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [23]:
x_view[0] = 10
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [24]:
# view -> contigious tensor (ramde veriler sıralı mı?)

In [26]:
x = torch.tensor([[1,2,3],
                  [3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [28]:
x.is_contiguous()

True

In [30]:
y = x.T

In [32]:
y

tensor([[1, 3],
        [2, 4],
        [3, 5]])

In [35]:
y.is_contiguous() # transpoze edilmesi durumunda contiguous durumu bozulabilir.

False

In [36]:
x.view(1,6)

tensor([[1, 2, 3, 3, 4, 5]])

In [38]:
# y.view(1,6) # view contiguous olmadığı için çalışmaz.

In [39]:
y.reshape(1,6)

tensor([[1, 3, 2, 4, 3, 5]])

In [47]:
x_stack = torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[1, 2, 3],
         [3, 4, 5]],

        [[1, 2, 3],
         [3, 4, 5]],

        [[1, 2, 3],
         [3, 4, 5]]])

In [46]:
torch.stack([x,x,x,x],dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[3, 4, 5],
         [3, 4, 5],
         [3, 4, 5],
         [3, 4, 5]]])

In [48]:
x_stack.shape

torch.Size([4, 2, 3])

In [49]:
# squeeze & unsqueeze

In [50]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [51]:
x.shape

torch.Size([2, 3])

In [52]:
x.ndim

2

In [59]:
x.squeeze()

tensor([[1, 2, 3],
        [3, 4, 5]])

In [60]:
x.squeeze().shape

torch.Size([2, 3])

In [61]:
x = torch.tensor([[1,2,3]])
x

tensor([[1, 2, 3]])

In [62]:
x.shape

torch.Size([1, 3])

In [63]:
x.ndim

2

In [65]:
x.squeeze() # boş bir boyut görüyorsa ondan kurtluyor.

tensor([1, 2, 3])

In [68]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [69]:
x.shape

torch.Size([2, 3])

In [70]:
x.ndim

2

In [72]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [75]:
x.unsqueeze(dim=0) # bir boyut daha ekliyor.

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [74]:
x.unsqueeze(dim=0).ndim

3

In [76]:
# permute -> boyutların yerlerini değiştiriyor.

In [78]:
x = torch.rand(size=(224,224,3))

In [80]:
x.shape

torch.Size([224, 224, 3])

In [86]:
x_permuted = x.permute(2,0,1) # axis 0->1, 1->2, 2->0

In [87]:
x_permuted.shape

torch.Size([3, 224, 224])

In [89]:
# indexing & slicing

In [90]:
a = torch.arange(1,10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a = a.reshape(1,1,3,3) # squeeze yapmış gibi.

In [101]:
a[0][0][0][0]

tensor(1)

In [102]:
a[0,0,0,0]

tensor(1)

In [103]:
a.ndim

4

In [112]:
a[:,0,0,0]

tensor([1])

In [116]:
a

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [126]:
a[:,:,1,1]

tensor([[5]])

In [127]:
# random seed

In [141]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])