In [1]:
import torch

In [10]:
torch.cuda.is_available() # for nvidia gpu

True

In [11]:
torch.backends.mps.is_available() # for macbook

False

In [15]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [16]:
device

'cuda'

In [17]:
tensor = torch.tensor([1,2,3])

In [18]:
tensor

tensor([1, 2, 3])

In [19]:
tensor.device

device(type='cpu')

In [22]:
#manual

In [23]:
tensor_device = tensor.to(device)

In [24]:
tensor_device

tensor([1, 2, 3], device='cuda:0')

In [25]:
tensor.numpy()

array([1, 2, 3])

In [28]:
# tensor_device.numpy()  # tensor gpu'da numpy cpu da, uyumsuzlar. 

In [29]:
tensor_device.cpu() # geri cpu'ya alıyoruz.

tensor([1, 2, 3])

In [30]:
# context manager

In [31]:
with torch.device(device):
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20,30)

In [32]:
tensor2.device

device(type='cuda', index=0)

In [34]:
layer.weight.device

device(type='cuda', index=0)

In [35]:
# torch.set_default_device

In [36]:
device

'cuda'

In [37]:
torch.set_default_device(device)

In [39]:
tensor4 = torch.tensor([1,2,3])
print(tensor4.device)
layer4 = torch.nn.Linear(10,20)
print(layer4.weight.device)

cuda:0
cuda:0


In [20]:
tensor_device = torch.tensor([1,2,3],device="cuda")

In [21]:
tensor_device.device

device(type='cuda', index=0)